# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Huanlv
    Domain: huanlv.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Huanlv
    Domain: huanlv.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  
  - Name: Akachain
    Domain: akachain.io
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
